//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Port.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serial_Port.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All Files benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string all_file {
            get {
                return ResourceManager.GetString("all_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Detail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string appdetail {
            get {
                return ResourceManager.GetString("appdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autoconfig Proccess benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string autocfg_proccess {
            get {
                return ResourceManager.GetString("autocfg_proccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Screen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cmd_screen {
            get {
                return ResourceManager.GetString("cmd_screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complate benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Complate {
            get {
                return ResourceManager.GetString("Complate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string con_type {
            get {
                return ResourceManager.GetString("con_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string connect_errormsg {
            get {
                return ResourceManager.GetString("connect_errormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string connect_setting {
            get {
                return ResourceManager.GetString("connect_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Settings Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string connect_setting_error {
            get {
                return ResourceManager.GetString("connect_setting_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open serial  port: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string connected_mbox_error {
            get {
                return ResourceManager.GetString("connected_mbox_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defines benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string defines {
            get {
                return ResourceManager.GetString("defines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No devices connected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string device_connect_errormsg {
            get {
                return ResourceManager.GetString("device_connect_errormsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Devices benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string devices {
            get {
                return ResourceManager.GetString("devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End Line benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string endline {
            get {
                return ResourceManager.GetString("endline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List is empty or no items are selected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error_select_list {
            get {
                return ResourceManager.GetString("error_select_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select file benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string file_select_message {
            get {
                return ResourceManager.GetString("file_select_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get System List (apppath\config\syslist.txt) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string get_syslist {
            get {
                return ResourceManager.GetString("get_syslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getway IP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string getwayIP {
            get {
                return ResourceManager.GetString("getwayIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Command is Between Line benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string insert_between_cmd {
            get {
                return ResourceManager.GetString("insert_between_cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Command is EndLine benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string insert_cmd_endlist {
            get {
                return ResourceManager.GetString("insert_cmd_endlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert From Command Line benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string insertcmd {
            get {
                return ResourceManager.GetString("insertcmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path Invalid. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string invalid_file_path {
            get {
                return ResourceManager.GetString("invalid_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP address is not valid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ip_error {
            get {
                return ResourceManager.GetString("ip_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPs benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string IPs_found {
            get {
                return ResourceManager.GetString("IPs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Languages benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Down benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string move_down {
            get {
                return ResourceManager.GetString("move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Up benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Move_up {
            get {
                return ResourceManager.GetString("Move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Closed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string port_closed {
            get {
                return ResourceManager.GetString("port_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find ports benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string port_error {
            get {
                return ResourceManager.GetString("port_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string portlist {
            get {
                return ResourceManager.GetString("portlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Config benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string preconfig {
            get {
                return ResourceManager.GetString("preconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh File List ( app_path\config) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string refresh_filelist {
            get {
                return ResourceManager.GetString("refresh_filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh Port List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string refreshport {
            get {
                return ResourceManager.GetString("refreshport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Selected Line benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string replace_line {
            get {
                return ResourceManager.GetString("replace_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save succesfully benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string save_ok {
            get {
                return ResourceManager.GetString("save_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string saveas {
            get {
                return ResourceManager.GetString("saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as Command File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string saveas_comfile {
            get {
                return ResourceManager.GetString("saveas_comfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search this area benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start from selected row benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string select_row {
            get {
                return ResourceManager.GetString("select_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Space to be added with double click benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string spaceadd {
            get {
                return ResourceManager.GetString("spaceadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Configuration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string start_cfg {
            get {
                return ResourceManager.GetString("start_cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System IP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sys_ip {
            get {
                return ResourceManager.GetString("sys_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Names benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sysfound {
            get {
                return ResourceManager.GetString("sysfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sysname {
            get {
                return ResourceManager.GetString("sysname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Templates benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string templates {
            get {
                return ResourceManager.GetString("templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample Command Template benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string templates_command {
            get {
                return ResourceManager.GetString("templates_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample Definition Template benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string templates_definition {
            get {
                return ResourceManager.GetString("templates_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample System List Template benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string templates_syslist {
            get {
                return ResourceManager.GetString("templates_syslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string text_file {
            get {
                return ResourceManager.GetString("text_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An undetermined error has occurred. Check whether your port connection is open or you are connected to the correct port. Check your connected cables and devices. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string unknown_connect_error {
            get {
                return ResourceManager.GetString("unknown_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command File Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string up_com_file {
            get {
                return ResourceManager.GetString("up_com_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable Definitions benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string var_def {
            get {
                return ResourceManager.GetString("var_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file already exists. Do you want to overwrite? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning_file {
            get {
                return ResourceManager.GetString("warning_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file already exist. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string warning_file_shortversion {
            get {
                return ResourceManager.GetString("warning_file_shortversion", resourceCulture);
            }
        }
    }
}
